#!/bin/bash
# /etc/init.d/alarmclockd

### BEGIN INIT INFO
# Provides:          alarmclock
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage early-riser
### END INIT INFO

APP=early-riser

PATH="/usr/local/bin/$APP"

case "$1" in
    start)
        echo "starting alarm clock"
        /usr/bin/amixer sset PCM,0 100%
        $PATH &
        ;;
    stop)
        echo "stopping alarm clock"
        /usr/bin/killall -SIGINT $APP
        ;;
    *)
        echo "Usage: /etc/init.d/alarmclockd start|stop"
        exit 1
        ;;
esac

exit 0
